### ISSUE TITLE
Unable to run 

### ISSUE THREAD

**Issue by raghavzns** [joeVenner/FaceRecognition-GUI-APP#17]
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "app-gui.py", line 209, in openwebcam
    main_app(self.controller.active_name)
  File "/home/raghav/Documents/FaceRecognition-GUI-APP/Detector.py", line 10, in main_app
    recognizer.read(f"./data/classifiers/{name}_classifier.xml")
cv2.error: OpenCV(4.2.0) /io/opencv_contrib/modules/face/src/facerec.cpp:61: error: (-2:Unspecified error) File can't be opened for reading! in function 'read'

```

**Comment by joeVenner** [comment]
Check this! 
https://stackoverflow.com/questions/48673885/opencv-error-file-cannot-be-opened-for-reading-cvfacefacerecognizerread-wi
